# Generated by Django 4.0.4 on 2022-04-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_remove_meetup_participant_delete_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='location',
        ),
    ]
