# Generated by Django 4.0.4 on 2022-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_participant_meetup_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-04-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizerEmail',
            field=models.EmailField(default='xquare@yahoo.com', max_length=254),
            preserve_default=False,
        ),
    ]
